@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "Пользователь", "Житель дома, использующий систему для управления отоплением")
Person(installer, "Техник", "Специалист по установке и подключению оборудования")

System(system, "Система 'Тёплый дом'", "Монолитное приложение на Go, управляющее отоплением")

System_Ext(sensor, "Датчик температуры", "Устройство в доме, передающее данные по запросу и управляющее системой отопления")

Rel(user, system, "Управляет отоплением, просматривает температуру", "Веб приложение")
Rel(installer, system, "Подключает систему к дому", "Вручную")
Rel(system, sensor, "Запрашивает текущую температуру", "Синхронный HTTP-запрос")
Rel(system, sensor, "Посылает команды включить/выключить отопление", "Синхронный HTTP-запрос")

@enduml
